POST https://nexar-eyn4.onrender.com/api/v1/keys/generate
Content-Type: application/json


###
POST http://localhost:4040/api/v1/keys/generate
Content-Type: application/json

###
GET http://localhost:4040/api/v1/keys/validate/?apikey=kjasdhkjdsh
Content-Type: application/json


###
GET http://localhost:4040/api/v1/keys/validate/
Content-Type: application/json
x-api-key: OGQyNWI5YjZkZDIyMmIzNjoxNzYzMTYzMjQzNjgwOmU3Y2RlMDFjMmM1NDFjMTk5YzI3ZDBhZTYzOWU3NzEzNzAxMWRiYTI3MDNlZWQ0ODVhODI4YTgyYjBiODU2Yzg
