export enum AFFILIATES {
  EXOLIX = 'exolix',
  // FIXED_FLOAT = 'fixedfloat',
  SWAPUZ = 'swapuz',
  SIMPLE_SWAP = 'simpleswap',
  CHANGENOW = 'changenow',
  COINGECKO = 'coingecko',
}

export const AFFILIATE_DATA = {
  EXOLIX: {
    name: AFFILIATES.EXOLIX,
    baseUrl: process.env.EXOLIX_API_URL, // e.g., 'https://api.exolix.com/v1/'
    apiKey: process.env.EXOLIX_API_KEY || '',
    endpoints: {
      tokens: 'currencies',
      chains: 'currencies/networks',
      getRate: 'rate',
      getTransactions: 'transactions',
      getTransactionById: 'transactions/', // expects ID as param
      createExchangeTxn: 'transactions', // POST with body
    },
  },
  CHANGENOW: {
    name: AFFILIATES.CHANGENOW,
    baseUrl: process.env.CHANGENOW_URL, // e.g., 'https://api.changenow.io/v1/'
    apiKey: process.env.CHANGENOW_API_KEY || '',
    endpoints: {
      tokens: 'currencies?active=true&fixedRate=true',
      getTransactions: 'exchanges', // query: from, to, amount, fromNetwork, toNetwork
      getTransactionById: 'exchanges/', // expects public ID as param
      confirmTransaction: 'exchanges', // POST with body
      getRate: 'ranges',
    },
  },
  COINGECKO: {
    name: AFFILIATES.COINGECKO,
    baseUrl: process.env.COINGECKO_URL,
    apiKey: process.env.COINGECKO_API_KEY,
    endpoints: {
      tokens: '',
    },
  },
};

export const NETWORK_MAPPINGS: { [key: string]: string } = {
  erc20: 'ETH',
  eth: 'ETH',
  btc: 'BTC',
  bitcoin: 'BTC',
  ethereum: 'ETH',
  trc20: 'TRX',
  bsc: 'BSC',
  sol: 'SOL',
  matic: 'MATIC',
  algo: 'ALGO',
  arc20: 'AVAX',
  arb: 'ARBITRUM',
  op: 'OPTIMISM',
  ton: 'TON',
  celo: 'CELO',
  base: 'BASE',
  manta: 'MANTA',
  lna: 'LNA',
  'binance-smart-chain': 'BSC',
  'polygon-pos': 'POLYGON',
  avalanche: 'AVAX',
  'arbitrum-one': 'ARBITRUM',
  'optimistic-ethereum': 'OPTIMISM',
  xdai: 'XDAI',
  fantom: 'FANTOM',
  'harmony-shard-0': 'HARMONY',
  solana: 'SOL',
  'near-protocol': 'NEAR',
  ronin: 'RONIN',
  'klay-token': 'KLAYTN',
  terra: 'TERRA',
  'terra-2': 'TERRA2',
  cosmos: 'COSMOS',
  osmosis: 'OSMOSIS',
  polkadot: 'POLKADOT',
  cardano: 'CARDANO',
  tron: 'TRX',
  eos: 'EOS',
  tezos: 'TEZOS',
  algorand: 'ALGO',
  stellar: 'XLM',
  litecoin: 'LTC',
  'bitcoin-cash': 'BCH',
  dogecoin: 'DOGE',
  ripple: 'XRP',
  monero: 'XMR',
  zcash: 'ZEC',
  dash: 'DASH',
  'the-open-network': 'TON',
  aptos: 'APTOS',
  sui: 'SUI',
  linea: 'LINEA',
  scroll: 'SCROLL',
  mantle: 'MANTLE',
  'metis-andromeda': 'METIS',
  moonbeam: 'MOONBEAM',
  moonriver: 'MOONRIVER',
  cronos: 'CRONOS',
  'okex-chain': 'OKT',
  'huobi-token': 'HT',
  'kucoin-community-chain': 'KCC',
  energi: 'NRG',
  elrond: 'EGLD',
  multiversx: 'MULTIVERSX',
  neo: 'NEO',
  ontology: 'ONTOLOGY',
  vechain: 'VET',
  icon: 'ICX',
  zilliqa: 'ZIL',
  waves: 'WAVES',
  nano: 'NANO',
  iota: 'IOTA',
  'hedera-hashgraph': 'HBAR',
  secret: 'SCRT',
  'oasis-network': 'ROSE',
  theta: 'THETA',
  thorchain: 'RUNE',
  kusama: 'KSM',
  atom: 'atom',
  injective: 'INJ',
  kava: 'KAVA',
  persistence: 'XPRT',
  regen: 'REGEN',
  'iris-network': 'IRIS',
  sentinel: 'DVPN',
  akash: 'AKT',
  stargaze: 'STARS',
  juno: 'JUNO',
  comdex: 'CMDX',
  assetmantle: 'MNTL',
  evmos: 'EVMOS',
  umee: 'UMEE',
  desmos: 'DSM',
  'gravity-bridge': 'GRAV',
  crescent: 'CRE',
  nyx: 'NYX',
  quicksilver: 'QCK',
  stride: 'STRD',
  neutron: 'NTRN',
  noble: 'NOBLE',
};
