POST http://localhost:4040/api/transfer-new/create_transaction
Content-Type: application/json
x-api-key: OGQyNWI5YjZkZDIyMmIzNjoxNzYzMTYzMjQzNjgwOmU3Y2RlMDFjMmM1NDFjMTk5YzI3ZDBhZTYzOWU3NzEzNzAxMWRiYTI3MDNlZWQ0ODVhODI4YTgyYjBiODU2Yzg

{
    "token": "ETH",
    "recipientAddress": "0x925b098f9e5f2349926E1de19205b927237fbc46",
    "amount": 0.0015, 
    "isTestnet": true
}


###
POST http://localhost:4040/api/transfer-new/start_transfer
Content-Type: application/json
x-api-key: OGQyNWI5YjZkZDIyMmIzNjoxNzYzMTYzMjQzNjgwOmU3Y2RlMDFjMmM1NDFjMTk5YzI3ZDBhZTYzOWU3NzEzNzAxMWRiYTI3MDNlZWQ0ODVhODI4YTgyYjBiODU2Yzg

{
    "transactionId": "en7b39h900xiw8"
}