GET http://localhost:3000/api/v1/swap/tokens
Content-Type: application/json

###
GET https://nexar-eyn4.onrender.com/api/v1/swap/tokens
Content-Type: application/json

###
GET http://localhost:3000/api/v1/
Content-Type: application/json

###
GET http://localhost:3000/api/v1/swap/min-amount/ade_tinu
Content-Type: application/json

###
GET http://localhost:3000/api/v1/swap/exchange-amount/230/usdterc20_usdtsol
Content-Type: application/json


###
GET http://localhost:4040/api/v1/swap/transactions/6a22bade776e7c
Content-Type: application/json

###
GET http://localhost:4040/api/v1/swap/transactions/inApp/6a22bade776e7c
Content-Type: application/json

###
GET http://localhost:4040/api/v1/swap/transactions/6a22bade776e86
Content-Type: application/json

###
POST http://localhost:4040/api/v1/swap/transactions
Content-Type: application/json

{
  "from": "btc",
  "to": "eth",
  "address": "0x57f31ad4b64095347F87eDB1675566DAfF5EC886",
  "amount": "0.00123",
  "extraId": "",
  "userId": "",
  "contactEmail": "",
  "refundAddress": "",
  "refundExtraId": ""
}



