GET http://localhost:4040/api/v2/swap/tokens?page=8
Content-Type: application/json
Accept: application/json
x-api-key: OGQyNWI5YjZkZDIyMmIzNjoxNzYzMTYzMjQzNjgwOmU3Y2RlMDFjMmM1NDFjMTk5YzI3ZDBhZTYzOWU3NzEzNzAxMWRiYTI3MDNlZWQ0ODVhODI4YTgyYjBiODU2Yzg

###
GET http://localhost:4040/api/v2/swap/tokens?search=bsc
Content-Type: application/json
Accept: application/json
x-api-key: OGQyNWI5YjZkZDIyMmIzNjoxNzYzMTYzMjQzNjgwOmU3Y2RlMDFjMmM1NDFjMTk5YzI3ZDBhZTYzOWU3NzEzNzAxMWRiYTI3MDNlZWQ0ODVhODI4YTgyYjBiODU2Yzg

###
POST http://localhost:4040/api/v2/swap/swap_request
Content-Type: application/json
Accept: application/json
x-api-key: OGQyNWI5YjZkZDIyMmIzNjoxNzYzMTYzMjQzNjgwOmU3Y2RlMDFjMmM1NDFjMTk5YzI3ZDBhZTYzOWU3NzEzNzAxMWRiYTI3MDNlZWQ0ODVhODI4YTgyYjBiODU2Yzg

{
     "direction": "SEND",
     "from_amount": "0.015",
     "from_currency": "BTC",
     "from_network": "BTC",
     "to_currency": "ETH",
     "to_network": "ETH",
     "init": true, 
     "uuid_request": "yh43aee4-0076-400e-a8c9-ered90dc6456"
}

###
POST http://localhost:4040/api/v2/swap/start_swap
Content-Type: application/json
Accept: application/json
x-api-key: OGQyNWI5YjZkZDIyMmIzNjoxNzYzMTYzMjQzNjgwOmU3Y2RlMDFjMmM1NDFjMTk5YzI3ZDBhZTYzOWU3NzEzNzAxMWRiYTI3MDNlZWQ0ODVhODI4YTgyYjBiODU2Yzg

{
     "uuid_request": "yh43aee4-0076-400e-a8c9-ered90dc6456",
     "recipient_address": "0x925b098f9e5f2349926E1de19205b927237fbc46",
     "selected_provider": "exolix",
     "selected_quote_uid": "1757264586342-30e8urolb"
}

### Get Transaction
GET http://localhost:4040/api/v2/swap/transaction/yh43aee4-0076-400e-a8c9-ered90dc6456
Content-Type: application/json
Accept: application/json
x-api-key: OGQyNWI5YjZkZDIyMmIzNjoxNzYzMTYzMjQzNjgwOmU3Y2RlMDFjMmM1NDFjMTk5YzI3ZDBhZTYzOWU3NzEzNzAxMWRiYTI3MDNlZWQ0ODVhODI4YTgyYjBiODU2Yzg

###   Partners gets Exolix
GET https://exolix.com/api/v2/currencies?withNetworks=true&page=1&size=100
Content-Type: application/json
Accept: application/json
Authorization: 

# ### Fixed Float
# POST https://ff.io/api/v2/ccies
# Content-Type: application/json
# Accept: application/json
# X-API-KEY: 
# X-API-SIGN: 

# ### SWAPUZ
# GET https://api.swapuz.com/api/home/v1/coins
# Content-Type: application/json
# Accept: application/json
# Api-Key:

# ### Simple Swap
# GET https://api.simpleswap.io/get_all_currencies?api_key=a826bbc0-9549-4749-a718-59a8d30aa9a7
# Content-Type: application/json
# Accept: application/json

###
GET https://api.changenow.io/v1/currencies?active=true&fixedRate=true
Content-Type: application/json
Accept: application/json 
